### ISSUE TITLE
Consider changing candid types from `candid` to `ic_cdk::export::candid`

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#1086]
Right now we depend on the candid crate directly. `ic-cdk` already has a candid version that it exports and the two are tightly coupled so we should maybe just use the one from `ic-cdk`.

There might be other conflicts with the other crates. So, consider all the ramifications before proceeding.

**Comment by lastmjs** [comment]
The ic-cdk has made this choice for us starting in 0.10.0 I believe, we must now depend directly on candid::
