### ISSUE TITLE
Differentiate between number and float64; and text and string

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#1108]
The runtime errors epic highlighted that if you return `number` we actually only have errors that refer to it as a `float64`. Similar issues with text/string. So, we should probably create alias wrapper type things that let us distinguish between the two. Then we should update the error messages so that they actually say the right thing.

Specifically, we need to handle:

- [ ] string and text
- [ ] number and float64
- [ ] BigInt and Int

_Null/Undefined might also be related to this but I'm less sure on that._

**Comment by bdemann** [comment]
Might be related to https://github.com/demergent-labs/azle/issues/1118
