### ISSUE TITLE
Ledger implementation

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#114]
This might be a great example project to build. Create an implementation of the ledger standard (ICP/SNS/probably most fungible tokens going forward on the IC).

Here's the source code: https://github.com/dfinity/ic/tree/master/rs/rosetta-api/ledger_canister
Here's the did: https://github.com/dfinity/ic/blob/master/rs/rosetta-api/ledger_canister/ledger.did

**Comment by dansteren** [comment]
Implemented ICRC-1 instead here: https://github.com/demergent-labs/ICRC-1
