### ISSUE TITLE
Clarify unused type error messages

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#1181]
Given the following canister:

```ts
import { $query } from 'azle';

type CandidIncompatibleType = {
    problem: string;
};

$query;
export function method(): CandidIncompatibleType {
    return {
        problem: "It's easy to forget to wrap this with Record<>"
    };
}
```

When running `npx azle myCanister` (or `dfx deploy`)

The following is currently output:

```plaintext
$ npx azle myCanister

Building canister myCanister

[1/2] 🔨 Compiling TypeScript...
Canister compilation failed:
The type CandidIncompatibleType is used, but never defined.
Compilation failed with status: 6
```

This stems from the fact that we only parse complex types that are annotated with `Record` or `Variant`. The wording of this error message is misleading however because the type is defined, it's just not candid compatible.

We need to update this error message to something more like:

```plaintext
The type CandidIncompatibleType is used, but is not candid compatible.
Try wrapping it with `Record` or `Variant`.
```

We could consider showing where it was used, where it was defined, and a snippet of how to fix it.

**Comment by lastmjs** [comment]
This is no longer an issue, TypeScript will give type errors if Records are created incorrectly and if query or update or other methods don't accept CandidTypes
