### ISSUE TITLE
Inter-canister query calls (ICQC)

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#124]
Right now the `QueryAsync` type and functionality has been turned off because the IC does not have a general ICQC solution. Once this is fixed, let's enable the functionality:

Resources:
- https://forum.dfinity.org/t/inter-canister-query-calls-community-consideration/6754
- https://forum.dfinity.org/t/proposal-composite-queries/15979
- https://docs.rs/ic-cdk-macros/latest/ic_cdk_macros/attr.query.html

**Comment by dansteren** [comment]
I just encountered a weird bug. If you make a self-referencing cross-canister call (i.e. a call back to the same canister) then dfx v0.12.0 will complain with the following error message: 

Given:

![Image](https://user-images.githubusercontent.com/5455419/214443996-2464d754-f861-4293-b37d-e243bbd2ab3a.png)


When calling the self-calling method as shown here:

![Image](https://user-images.githubusercontent.com/5455419/214443904-855eebb5-a2d0-46db-a043-4261b17c906c.png)

Then the canister spits out the following error message:

> IC0517: Loop detected.  MVP inter-canister queries do not support loops.


Changing the canister method to be an Update removes the problem.
