### ISSUE TITLE
IC APIs

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#134]
I will split these up into issues, I need to put the initial infrastructure in place for some of these before I solicit help. Let's do them in order of priority, some I think are more important than others. For example, the course stable save and get

- [x] #234
- [x] #388
- [x] #373
- [x] #385
- [x] #389
- [x] #390
- [x] #391
- [x] #374 
- [x] #392
- [x] #393
- [x] #394
- [x] #375
- [x] #387
- [x] #462 
- [x] #463
- [x] #464
- [x] #395
- [x] #361
- [x] #386
- [x] #383
- [x] #378
- [x] #376
- [x] #377
- [x] #379
- [x] #380
- [x] #381
- [x] #382
- [x] #384
- [x] call: https://docs.rs/ic-cdk/latest/ic_cdk/api/call/fn.call.html
- [x] call_raw: https://docs.rs/ic-cdk/latest/ic_cdk/api/call/fn.call_raw.html
- [x] ic_cdk::storage::delete: https://docs.rs/ic-cdk/latest/ic_cdk/storage/fn.delete.html
- [x] ic_cdk::storage::get: https://docs.rs/ic-cdk/latest/ic_cdk/storage/fn.get.html
- [x] ic_cdk::storage::get_mut: https://docs.rs/ic-cdk/latest/ic_cdk/storage/fn.get_mut.html
- [x] ic_cdk::storage::stable_restore: https://docs.rs/ic-cdk/latest/ic_cdk/storage/fn.stable_restore.html
- [x] ic_cdk::storage::stable_save: https://docs.rs/ic-cdk/latest/ic_cdk/storage/fn.stable_save.html

**Comment by dansteren** [comment]
We've implemented all of these except `arg_data` and `result` which will be completed with https://github.com/demergent-labs/azle/issues/496. Although that work is related, it will likely take a non-trivial amount of effort so I'm not including it in this "epic". That way we can close this out with the 0.5.0 milestone.
