### ISSUE TITLE
‘npx azle new ‘ command doesn’t work in v18.0.1

### ISSUE THREAD

**Issue by maemil** [demergent-labs/azle#1358]
Hello. I'm having trouble setting up my azle project to create a canister smart contract. Here are the issues I'm facing:

## Note
Until version 17, I was able to use azle by running the `npx azle new` command without the need for a global installation. 

However, version 18, additional steps are required.

### Environment
- Apple M2 Pro
- Ventura 13.4.1

## Issue 1
When I run the `npx azle new [PROJECT_NAME]` command, the project setup doesn't proceed, and the command is terminated without any error code.

## Issue 2
I took the following steps:
1. `npm i --g azle`
2. `npx azle new [PROJECT_NAME]`
3. `npm run canister_deploy_local` within the project directory.

In this situation, the **.azle** directory is not created, and the deployment is not successful.

## Issue 3
In Issue 2, I encountered an error stating that Azle could not be imported, so I separately installed Azle for the project.

1. `npm i --g azle`
2. `npx azle new [PROJECT_NAME]`
3. `npm i azle`
4. `npm run canister_deploy_local`

When I followed these steps, the deployment was completed successfully.

**Comment by lastmjs** [comment]
Thank you for reporting these issues. I will be working on 1 today and I'm hoping that fixes the main problem.

Usually to get around this issue (which we just discovered at a hackathon this weekend), we suggest simply using the Methodical Start from The Azle Book. The project works fine if you just make your files manually.

Tell me why you decided to install Azle globally? I generally don't recommend this and we don't plan to support it.

Local install should always work.

**Comment by lastmjs** [comment]
Ah yes, for issue 2, you must always have Azle installed locally, I don't think that's an issue that's just how it's designed to work. If that's a problem for some reason please let us know.

So what I'm seeing is that the only real problem is `npx azle new` isn't working like it used to.

We're well aware and are just getting back to programming today, so I'll have it fixed shortly.

**Comment by lastmjs** [comment]
Also the problem for some reason is intermittent, I had tested azle new in my machine and at least one other if I'm not mistaken, but it didn't present on native Ubuntu.

**Comment by lastmjs** [comment]
Here's the fix for `npx azle new`: https://github.com/demergent-labs/azle/pull/1366

**Comment by lastmjs** [comment]
This has been resolved in Azle 0.18.2. I recommend completely uninstalling azle globally. `npx azle new` should function as desired.
