### ISSUE TITLE
Understand the root cause of the principal problem

### ISSUE THREAD

**Issue by bdemann** [demergent-labs/azle#1443]
When we are comparing two principals (especially using deepEqual) they always look unequal if they come from different sources. Even if they are exactly the same, it seems that there is some sort of invisible data that prohibits them from being actually compared against each other. As a result we have to be very careful that every time we are importing Principal, it is not only coming from the same version of Principal but from the same installation of Principal. 

We can't use a custom equal from deepEqual to overcome this because it would need to use a compareObject function (from the create custom deep equal) and it deems them unequal before it even gets to that point.

We had to install @dfinity/agent as a dev dependency of azle instead of locally on each property test because of this problem. And when creating the Principal valueLiteral we have to explicitly import from @dfinity/principal instead of getting Principal from azle because that was also throwing it off.

**Comment by lastmjs** [comment]
I'm still not sure on the root cause, but switching to another library has solved the issue
