### ISSUE TITLE
Function for pattern matching.

### ISSUE THREAD

**Issue by geeorgipehlianov1** [demergent-labs/azle#1455]
I am using Azle version 0.18.6 and I want to use function for pattern matching. I see that in earlier versions 'match' was used but now when I try to import it from 'azle' I receive the following error 'Module '"azle"' has no exported member 'match'. Can someone suggest me any other function to use for pattern matching.

**Comment by lastmjs** [comment]
We have removed that functionality, Azle will not be providing abstractions for pattern matching. You can create your own. We recommend just checking for the existence of a property for variants, `'prop' in MyVariant`, or `MyVariant.prop !== undefined`>.

Neither way is very elegant, but we've decided it's out of scope for Azle to provide this functionality.
