### ISSUE TITLE
Allow type aliases for all types

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#154]
```typescript
// export type SuperheroId = int32; // this is causing  Error: Could not generate Candid record for type alias declaration: [object Object]
```

Right now you can't make a type alias for everything, we need to exclude type aliases of certain types from triggering the Candid record process.

**Comment by cryptoisgood** [comment]
just dropping this comment to say I ran into this :)

`export type TokenId = nat; //Could not generate Candid record for type alias declaration`
