### ISSUE TITLE
Basic dao Motoko example

### ISSUE THREAD

**Issue by tarek-eg** [demergent-labs/azle#157]
There's a very useful [basic dao example ](https://github.com/dfinity/examples/tree/master/motoko/basic_dao)
Do you see any blockers on implementing that? Only thing I see is the heartbeat functionality but we can differ that to later when it's available.
It's more involved and would yield more insights on the limitations and bugs, I can start working on it if no objections.

**Comment by lastmjs** [comment]
Go ahead, heartbeat won't work like you said, and there is no access to stable storage yet either. It will be interesting to see how far you get.

**Comment by lastmjs** [comment]
BTW the testing infrastructure for examples should be coming today, working on it now

**Comment by tarek-eg** [comment]
> BTW the testing infrastructure for examples should be coming today, working on it now

That's a good news 🥳
