### ISSUE TITLE
Scrutinize the types in server.ts

### ISSUE THREAD

**Issue by bdemann** [demergent-labs/azle#1649]
There were a number of conflicts between Jordan's server.ts and Dan's http_gateway.ts. I did a rough conflict resolution of the two, putting all of the types into server.ts and removing http_gateway.ts. 

We would like to do a more thorough examination of those types and make sure that everything is as polished as we would like but at the time of making this ticket, it was a higher priority to resolve the conflicts and be able to move on.

**Comment by lastmjs** [comment]
This has been done to my satisfaction
