### ISSUE TITLE
Docker image execution on Mac seems very slow

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#1665]
On Ubuntu an Azle compilation on my machine using `candid_gen: http` takes about 7-10 seconds, but on Mac with Podman I have seen 25-45 seconds...not sure if there's anything we can do about speeding up the virtual machine on Mac.

**Comment by fredericrous** [comment]
<img width="718" alt="image" src="https://github.com/demergent-labs/azle/assets/702227/521cd3b5-5cc9-46d1-a619-5e38ac8ca6d8">

**Comment by lastmjs** [comment]
I'm not sure there's much we can do about it then...unless you have any ideas for a Docker-like experience native to Mac.

The problem we are solving with Docker/Podman is pulling down one universal environment with all of the OS/Rust dependencies installed and pre-compiled for as many developer environments as possible.

**Comment by fredericrous** [comment]
offer a NixOS alternative? NixOS might be too niche tho 😁

**Comment by lastmjs** [comment]
Podman has been removed as of Azle 0.23.0
