### ISSUE TITLE
fix rust vesion for azle compiler

### ISSUE THREAD

**Issue by fredericrous** [demergent-labs/azle#1671]
I got a rust compilation error because of mismatch version of the code with rust version in azle 0.20.1 that I solved by upgrading to 0.20.2. here is the error

<img width="1124" alt="image" src="https://github.com/demergent-labs/azle/assets/702227/29a77cd0-5dce-48f2-9484-a7a3e77ae138">

how about fixing the rust-version in https://github.com/demergent-labs/azle/edit/main/src/compiler/rust/canister/Cargo.toml with 
```
[package]
rust-version = "1.73.0"
```

**Comment by lastmjs** [comment]
Did you receive an error or just a warning?

**Comment by lastmjs** [comment]
Azle has been on Rust 1.73.0 for a long time, it is fixed to that version in the Dockerfile now, and Azle 0.20.1 also used that version, so I don't see how upgrading to Azle 0.20.2 would fix this issue

**Comment by fredericrous** [comment]
indeed the screenshot says warning and indeed if the version is fixed in the dockerfile it should be enough.
The full output was ending in an error and it looked like it was due to this warning. I cannot retry this now. Let's close this issue for now
