### ISSUE TITLE
On Mac show the initial Podman loading

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#1685]
Initial Podman loading on Mac takes a long time, we need to show progress to the user

**Comment by lastmjs** [comment]
Mac Podman is very slow, the virtual machine seems very slow...we must solve this problem somehow

**Comment by CodingFu** [comment]
I also tried to run with --native-compilation flag and it just doesn't work on my m3pro macbook pro
also, podman running in rosetta sigfaults on mac m3 pro.

I'm forced to develop and build on codespaces

**Comment by lastmjs** [comment]
Podman has been removed as of Azle 0.23.0
