### ISSUE TITLE
Live cross-canister calls example app

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#169]
What should I build to release along with the beta?

* Multisig timelock vault
* New Governance Bot?
* Azle NFT?
* Neuron voting multisig?

The governance bot has some pretty cool cross-canister calls, and it would allow me to see how much more expensive Azle is generally speaking than Rust.

The timelock vault would be okay...but the governance bot people are using now, so might be cool to do it

**Comment by filharvey** [comment]
Having an NFT which works like ERC271 and being able to list it on a couple of exchanges, would be nice.

But so would the Multisig timelock vault.

**Comment by lastmjs** [comment]
I agree, an NFT or the timelock vault would probably be best for a first try (well second try really, I released a fungible token called JSONIC back in October/November which was built with the earliest version of Azle).

I'm thinking the extendable token standard might be good to start with (the one Toniq has created). But I also want to build something today in just a few hours.

**Comment by filharvey** [comment]
Yes, the Toniq one was good. And has a market, so would be a good one for people.

Are you going to update JSONIC for the latest version as well? Or does it work alreay

**Comment by lastmjs** [comment]
JSONIC can't be updated, it has no controllers.

**Comment by filharvey** [comment]
Actually is Azle able to support upgrading of the canister?

**Comment by filharvey** [comment]
I guess I meant stable storage access. k

**Comment by tarek-eg** [comment]
Is cross-canister calls working now? Can I work on examples that require that like whoami or similar?

**Comment by lastmjs** [comment]
They're working on master or the release candidate npm packages

**Comment by lastmjs** [comment]
For development, if you have cloned the repo, you can do npm link in the root directory, and then in the example directory that you're working in do npm link azle. azle@0.1.0 will have cross canister calls enabled

**Comment by tarek-eg** [comment]
Great.
I want to work on the http_counter example in the meantime
https://github.com/dfinity/examples/tree/master/motoko/http_counter

**Comment by lastmjs** [comment]
Please make an issue and go ahead. I don't think that has any cross-canister calls in it though. I foresee multiple issues with that project right now, the HeaderField tuple type, the escape characters...maybe everything else will work. Good luck :)
