### ISSUE TITLE
Add bitcoinjs-lib test comment

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#1745]
`azle/examples/bitcoinjs-lib/test/pretest.ts` does an unexpected npm install on a sibling project. Please add a descriptive comment for newcomers to the codebase, as this is not an obvious thing.

**Comment by bdemann** [comment]
We were able to fix this in https://github.com/demergent-labs/azle/pull/1782 by adding the sibling project as a dependency in the package.json and by preserving symlinks in the azle build process, the tsconfig and ts-node
