### ISSUE TITLE
What is the roadmap for Azle to go live in production?

### ISSUE THREAD

**Issue by johnnynanjiang** [demergent-labs/azle#1808]
Hi folks,

Really look forward to using Azle in production for support JavaScript / TypeScript on ICP.

Just wonder is there a roadmap or plan for Azle to go live in production?

Thanks and regards,

**Comment by lastmjs** [comment]
We are scoping this out right now. It's very nuanced on what this means, as there are many possibilities before considering Azle production ready entirely. Our estimate is 3-9 months depending on what we fit in.

The idea right now is to move forward in the next 3ish months with getting the core ICP APIs in Azle production-ready, and then introducing an experimental flag for everything else.

So short overly-simplistic and probably overly-optimistic answer: 3ish months

**Comment by lastmjs** [comment]
But also, though we don't recommend Azle generally for production, you are free to make your own decision. We have many many (100s) of integration tests, a good amount of people using Azle, and we almost never receive bug reports outside of the installation/build process. Obviously that doesn't mean it's safe for general-purpose use, but perhaps your use-case based on your own analysis and safe-guards could be okay, at your entire discretion.

**Comment by johnnynanjiang** [comment]
Thanks @lastmjs for the clarifications, they help us estimate our side of work.

Regarding `we don't recommend Azle generally for production`, did you mean at current stage only? Or for other reasons?

Thanks and regards

**Comment by lastmjs** [comment]
Yes at the current stage, we aren't going to give a general recommendation for production use until we've accomplished the work that will make us feel comforting. Your use case and decision making process doesn't have to align with ours
