### ISSUE TITLE
Release 0.23.0 breaking changes vs. docs updates

### ISSUE THREAD

**Issue by BennyTheDev** [demergent-labs/azle#1921]
Hi,

release 0.23.0 includes breaking changes. e.g. "Canister" cannot be found on the azle package anymore.
If that was intentional, it would help to see reflected changes in the docs. Thank you.

**Comment by lastmjs** [comment]
Hi, breaking changes are detailed in the release notes for releases: https://github.com/demergent-labs/azle/releases/tag/0.23.0
