### ISSUE TITLE
Stable tests should run as experimental as well

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#2054]
If we have tests that are designed to just use stable syntax, we should still figure out how to run the tests with the experimental flag set. Here's more context:

"we need to run all stable syntax tests with the experimental flag as well, because stable syntax needs to work well even if the experimental flag is set. I'm dealing with a nasty class context (this) issue right now that only came up during manual testing"

**Comment by bdemann** [comment]
Done with https://github.com/demergent-labs/azle/pull/2191
