### ISSUE TITLE
It would be really nice if we could tell dfx where to put the generated TypeScript types

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#214]

**Comment by krpeacock** [comment]
You can!

Under the canister, you can add a "declarations" config

```
{
    "canisters": {
        "backend": {
            "type": "custom",
            "build": "npx azle backend",
            "root": "src",
            "ts": "src/backend.ts",
            "candid": "src/backend.did",
            "wasm": "target/wasm32-unknown-unknown/release/backend.wasm",
            "declarations": {
                "output": "<relative-path-here>"
            }
        }
    }
}
```

**Comment by lastmjs** [comment]
Can't wait to try this!

**Comment by lastmjs** [comment]
I'm trying it and it isn't working, I am on dfx `0.9.3`. What version will this work on?

**Comment by lastmjs** [comment]
I see, I need to run `dfx generate` to generate the types. It would be nice if this were part of the default `dfx build/deploy` process if the `declarations` object exists in `dfx.json`, it was confusing to me that it wasn't generating the types when I told it to.

Now I need to figure out a way to generate the types, but I am trying as much as possible to not force the user to have to do anything outside of `dfx` commands. Since there are no post-build scripts built into dfx, I am not sure where to put the dfx generate command...luckily I can control Azle and thus probably just put it in there for them if there is a declarations object present.
