### ISSUE TITLE
Allow inline types in Canister params and return types and StableBTreeMaps

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#221]
I don't think we allow inline type definitions in the params and return types of Canister definitions...I don't think this is blocking, but it would be nice to fix so we can have perfect compatibility with existing Candid files.

**Comment by lastmjs** [comment]
This might be fixed with the recent rewrite of the compiler, just test it out to check before closing.

**Comment by dansteren** [comment]
I've verified that inline types work in:

- [x] Canister method params
- [x] Canister method return types
- [ ] StableBTreeMaps
