### ISSUE TITLE
IC API canister_inspect_message

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#234]
ic_cdk_macros::inspect_message: https://docs.rs/ic-cdk-macros/0.5.1/ic_cdk_macros/attr.inspect_message.html

**Comment by dansteren** [comment]
Looks like the `inspect_message` method is designed to reject calls unless `ic_cdk::accept_message` is called from within this method. That will be added in #385. Without that, this can be implemented, but it will effectively deactivate all canister methods until `accept_message` is implemented.

**Comment by dansteren** [comment]
Additional relevant documentation: https://internetcomputer.org/docs/current/references/ic-interface-spec/#system-api-inspect-message

**Comment by dansteren** [comment]
Very interesting find... In motoko (as far as I can tell) the method is exposed as a function that returns a boolean. So if you return a `false` it rejects and a `true` accepts. I really like this. We should consider doing the same thing for azle, possibly the addition of rejecting if the user-defined method `throw`s.

See:

- https://github.com/dfinity/motoko/blob/master/doc/modules/language-guide/pages/language-manual.adoc#system-fields
- https://github.com/dfinity/motoko/blob/master/doc/modules/language-guide/pages/language-manual.adoc#inspect
