### ISSUE TITLE
M1 Mac build issue - could not compile `wabt-sys`

### ISSUE THREAD

**Issue by krpeacock** [demergent-labs/azle#237]
Issue can be observed in any example project, or even a blank ts entrypoint. Spec is 
OS: Monterey 12.3.1 
Processor: M1 Pro
Node: 16.14.0
Rust: 1.60.0

Full output is:

```
   Compiling wabt v0.10.0
error: failed to add native library /var/folders/xt/9tbb8ws541979mzdx2n9ms2r0000gn/T/cargo-installtXfSMj/release/build/wabt-sys-e78371680e273395/out/build/libwabt.a: file too small to be an archive

error: could not compile `wabt-sys` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `ic-cdk-optimizer v0.3.4`, intermediate artifacts can be found at `/var/folders/xt/9tbb8ws541979mzdx2n9ms2r0000gn/T/cargo-installtXfSMj`
Caused by:
  build failed
Error: Command failed: cd target/azle && cargo install ic-cdk-optimizer --root ..
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:902:15)
    at installRustDependencies (/Users/kyle/code/azle-rss/backend/node_modules/azle/src/azle.ts:60:13)
    at azle (/Users/kyle/code/azle-rss/backend/node_modules/azle/src/azle.ts:26:5)
    at Object.<anonymous> (/Users/kyle/code/azle-rss/backend/node_modules/azle/src/azle.ts:15:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (/Users/kyle/code/azle-rss/backend/node_modules/ts-node/src/index.ts:1365:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/kyle/code/azle-rss/backend/node_modules/ts-node/src/index.ts:1368:12)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  status: 101,
  signal: null,
  output: [ null, null, null ],
  pid: 97782,
  stdout: null,
  stderr: null
}
Error: The build step failed for canister 'rrkah-fqaaa-aaaaa-aaaaq-cai' with an embedded error: The custom tool failed.
```

**Comment by lastmjs** [comment]
Related: https://forum.dfinity.org/t/setup-internet-identity-locally-failed-macbook-m1/7684

**Comment by lastmjs** [comment]
Related: https://github.com/dfinity/internet-identity/pull/434

**Comment by lastmjs** [comment]
Are you able to compile and run `ic-cdk-optimizer` outside of Azle?

**Comment by lastmjs** [comment]
As a quick local fix you might try commenting this out: https://github.com/demergent-labs/azle/blob/main/src/azle.ts#L104 in node_modules/azle/src/azle.ts

**Comment by lastmjs** [comment]
Related: https://github.com/pepyakin/wabt-rs/issues/78

**Comment by lastmjs** [comment]
Someone else ran into an issue on an M1 with `swc`, adding this for future reference. FYI I don't have easy access to an M1 nor do any members of my team, so I'm not sure what I can do put try to help someone with an M1 figure this out. I might have a friend who can help in the future but no guarantees.

**Comment by cryptoisgood** [comment]
@krpeacock I wrapped dfx and the azle dependencies in a docker container. It's not really ready to be used but it be cool if you tried it to see if it gets you past this issue. 

https://www.npmjs.com/package/wdfx

**Comment by infu** [comment]
2min fix for M1

1. Install ic-cdk-optimizer standalone.
```
 cargo install ic-cdk-optimizer
```

2. Remove dependency install from https://github.com/demergent-labs/azle/blob/83090ffd0e5956a7e857a4d705b78a568f507365/src/azle.ts#L60
```
    // execSync(
    //     `cd target/azle && cargo install ic-cdk-optimizer --root ..`,
    //     { stdio: 'inherit' }
    // );
```
4. Change path to ic-cdk-optimiser https://github.com/demergent-labs/azle/blob/83090ffd0e5956a7e857a4d705b78a568f507365/src/azle.ts#L105
```
execSync(
        `~/.cargo/bin/ic-cdk-optimizer ./target/wasm32-unknown-unknown/release/${canisterName}.wasm -o ./target/wasm32-unknown-unknown/release/${canisterName}.wasm`,
        { stdio: 'inherit' }
    );
```

**Comment by lastmjs** [comment]
Thanks for this, we can probably get this fix into Azle soon. @krpeacock I would love to know if this works for you if you ever get a chance.

**Comment by lastmjs** [comment]
Could someone with an M1 could test building and deploying with `npm install azle@0.5.0-rc.0`? If that works then the issue should be resolved and we can get this into a major release.

**Comment by lastmjs** [comment]
I've had one person successfully use Azle on an M1 with this fix, so I'm considering it fixed for now

**Comment by lastmjs** [comment]
I'm hoping this will for sure be resolved once we switch Azle to ic-wasm, like we are planning to do in Kybra: https://github.com/demergent-labs/kybra/issues/42
