### ISSUE TITLE
Explain in caveats section that you cannot have properties named type

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#238]
type is reserved in Rust I believe, so you can't have fields named type

**Comment by lastmjs** [comment]
Related: https://github.com/demergent-labs/azle/issues/355

**Comment by lastmjs** [comment]
@dansteren look at this, another problem to solve similar to: https://github.com/demergent-labs/kybra/issues/99

**Comment by bdemann** [comment]
Thanks to https://github.com/demergent-labs/cdk_framework/issues/13 we actually CAN have properties named type
