### ISSUE TITLE
Seed the custom randomness

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#247]
- [x] Should we test that the seed works vs doesn't work?
- [x] What is the difference between seeding with 0s and seeding with actual randomness?

JavaScript `Math.random` works, but the value is always the same. I presume this is because our custom getrandom function doesn't actually have any randomness.

Resources:

 - https://forum.dfinity.org/t/cant-do-cross-canister-call-in-init-function/5187

**Comment by dansteren** [comment]
Alright, so to implement this, we basically need some way to call `raw_rand` one time near the start of the canister lifecycle. Potential solutions include:

- In the init/post-upgrade methods
- In a hearbeat
- In a method call
- Using the new timer API
- Use a to-be-developed post-init and post-post-upgrade hook.

The init/post-upgrade methods don't allow cross-canister calls (as highlighted in [this post](https://forum.dfinity.org/t/cant-do-cross-canister-call-in-init-function/5187)). The heartbeat would be too expensive and would potentially re-seed raw_rand. Making the developer manually call a `seed_randomness` method after deploy wouldn't be an acceptable developer experience.

This means we either use the new [timer API](https://docs.rs/ic-cdk/latest/ic_cdk/timer/index.html), or we wait for new hooks to be developed that allow cross-canister calls.

I'm creating a forum to see if those hooks would be useful, but we'll likely just use the timer api. The rust CDK has timers. According to [this post](https://forum.dfinity.org/t/heartbeat-improvements-timers-community-consideration/14201/61) it has been implemented on the IC side. It's in the `ic_cdk` [crate](https://docs.rs/ic-cdk/latest/ic_cdk/timer/index.html). The last piece we need is for it to be in DFX. I'm not seeing it in the [release notes](https://internetcomputer.org/docs/current/developer-docs/updates/release-notes/) for [v0.12.1](https://github.com/dfinity/sdk/releases/tag/0.12.1).

So, we're putting this back on the To-Do pile and will re-visit it once DFX has support.

**Comment by dansteren** [comment]
This has been [implemented in v0.12.1](https://forum.dfinity.org/t/heartbeat-improvements-timers-community-consideration/14201/73)

**Comment by dansteren** [comment]
This is blocked by #809.

**Comment by paulyoung** [comment]
If you’re still looking for a solution to this I had a couple of thoughts and think there could be a fairly transparent (if not completely transparent) workaround.

**Comment by lastmjs** [comment]
Actually Math.random does not return the same value very time, it only will seem to within successive query calls. If you call Math.random in successive update calls, then the randomness of the rng is remembered

**Comment by lastmjs** [comment]
@paulyoung Our plan right now is to set a timer in init and post_upgrade that immediately does a cross-canister call to retrieve randomness and seed the custom randomness function.
