### ISSUE TITLE
Check if `dfx deploy` urls work properly in dfx 10

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#352]
When deploying a canister with `dfx deploy` I expect dfx to output a url like `http://ryjl3-tyaaa-aaaaa-aaaba-cai.localhost:8000?id=rrkah-fqaaa-aaaaa-aaaaq-cai` instead of the current `http://127.0.0.1:8000/?canisterId=ryjl3-tyaaa-aaaaa-aaaba-cai&id=rrkah-fqaaa-aaaaa-aaaaq-cai`. We should work with dfinity to make this happen.

First check if this is fixed in DFX 10, and if not, then go find any relevant posts on the forum (Jordan might have one already) or make a new one.

**Comment by lastmjs** [comment]
Duplicate: https://github.com/demergent-labs/azle/issues/162

**Comment by dansteren** [comment]
URLs work, however not exactly as expected. We would prefer subdomains. We will follow up with Dfinity on this. Closing this for now though.
