### ISSUE TITLE
IC API result

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#361]
result: https://docs.rs/ic-cdk/latest/ic_cdk/api/call/fn.result.html

- [ ] This should be pretty simply once we have `arg_data` implemented. This just calls `reject_code` under the hood and returns `arg_data` if `reject_code` has no error, and returns `reject_message` otherwise.
- [ ] Here's the source: https://docs.rs/ic-cdk/latest/src/ic_cdk/api/call.rs.html#445-452

**Comment by dansteren** [comment]
This ticket is blocked. We cannot proceed until we fix arg_data.

I've started work on this but when I became blocked I pushed a WIP commit to store the work I'd done. See https://github.com/demergent-labs/azle/commit/9cfd3ba1bb2d218d959be89f1d585a1070caa0f4.
