### ISSUE TITLE
Issues with unreferenced StableStorage type aliases

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#366]
In the [life motoko example](60) the stable storage type contains a `state` property that should be of type `State` but because of this bug is currently set to `boolean[][]` which is the equivalent of the `State` alias. Because the `State` type is never referenced in the candid interface, the type isn't generated in rust. The result is the following error during compilation:

![Screenshot from 2022-05-31 10-43-59](https://user-images.githubusercontent.com/5455419/171228786-b6472b23-fde1-49d0-b385-39cf313a7996.png)

By using the raw primitive type instead of the alias rust is able to understand, so this is the current workaround.

**Comment by lastmjs** [comment]
Has this been resolved?
