### ISSUE TITLE
IC API method_name

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#388]
method_name: https://docs.rs/ic-cdk/latest/ic_cdk/api/call/fn.method_name.html

**Comment by lastmjs** [comment]
We need this resolved before we can move forward with writing tests: https://forum.dfinity.org/t/ic-cdk-method-name/8024

**Comment by lastmjs** [comment]
`method_name` can only be called from within `inspect_message`, so this issue depends on this issue: https://github.com/demergent-labs/azle/issues/234
