### ISSUE TITLE
spack issues

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#44]
We need these types of issues to be resolved so that imports work perfectly no matter where they are located and whether or not they are written in TypeScript:

* https://github.com/swc-project/swc/issues/3667
* https://github.com/swc-project/swc/issues/2574

**Comment by lastmjs** [comment]
I've moved on to esbuild for now, which is working great. Apparently spack isn't really ready for prime time

**Comment by georgekrax** [comment]
I believe this is a general issue about **Spack**, and should not be closed. Other developers seem to face similar struggles, which should be fixed. If you have found a new solution or anything related to it, please feel free to comment here!

**Comment by lastmjs** [comment]
Hey, I'm not sure if you're commenting in the correct repo. The issues above are still open in the spack repo, this is just the Azle TypeScript CDK for the Internet Computer, which will no longer use spack

**Comment by georgekrax** [comment]
@lastmjs Oh my bad 😅. You are right, do you have the link for the issue in the `swc-project` repo?

**Comment by lastmjs** [comment]
No problem! Both of the issues are linked here: https://github.com/demergent-labs/azle/issues/44#issue-1165505949
