### ISSUE TITLE
stable read optimizations

### ISSUE THREAD

**Issue by bdemann** [demergent-labs/azle#482]
stable_read and stable64_read are working, there are a couple of lines in stable_read.ts and stable64_read.ts that may need some optimizations

```let mut vec_buf: Vec<u8> = vec![0;length as usize];```
We need to see if we can make a mult& [] without having to initialize a vec with all zero values.

```return Ok(buf.to_vec().azle_into_js_value(_context));```
We need to see if to_vec will be efficient enough. If it's better than O(n) then we might be fine, otherwise we will need to figure out a better way of converting it.

**Comment by bdemann** [comment]
Solved with https://github.com/demergent-labs/azle/issues/488

**Comment by bdemann** [comment]
From the [rust documentation for vectors](https://doc.rust-lang.org/std/vec/struct.Vec.html):

> The [vec!](https://doc.rust-lang.org/std/macro.vec.html) macro is provided for convenient initialization
>
>It can initialize each element of a Vec<T> with a given value. This may be more efficient than performing allocation and initialization in separate steps, especially when initializing a vector of zeros:
>
>```let vec = vec![0; 5];
>assert_eq!(vec, [0, 0, 0, 0, 0]);
>
>// The following is equivalent, but potentially slower:
>let mut vec = Vec::with_capacity(5);
>vec.resize(5, 0);
>assert_eq!(vec, [0, 0, 0, 0, 0]);
>```
>For more information, see [Capacity and Reallocation](https://doc.rust-lang.org/std/vec/struct.Vec.html#capacity-and-reallocation).

I'll keep looking but I feel like this is implying that the vec! macro might be our best bet.

**Comment by bdemann** [comment]
I also found a set len function 
```
fn main() {
    let mut my_vec_macro: Vec<u8> = vec![0; 9];
    let mut my_vec_set_len: Vec<u8> = Vec::with_capacity(9);
    unsafe { my_vec_set_len.set_len(9); }
    println!("{:#?}", my_vec_macro);
    println!("{:#?}", my_vec_macro.len());
    println!("{:#?}", my_vec_set_len);
    println!("{:#?}", my_vec_set_len.len());
}
```
Output is
``` 
[
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
]
9
[
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
]
9
```

**Comment by lastmjs** [comment]
I think we're good on this for now, let's close this
