### ISSUE TITLE
counter Motoko example

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#52]
Recreate the counter Motoko example found here: https://github.com/dfinity/examples/tree/master/motoko/counter

Use the calc Motoko example as a template: https://github.com/demergent-labs/azle/tree/main/examples/motoko_examples/calc

A big reason for recreating the Motoko examples is to find limitations with Azle. Please document any limitations/bugs/errors you find in Azle in this issue thread.

**Comment by lastmjs** [comment]
@dansteren is working on this issue

**Comment by dansteren** [comment]
@lastmjs Yes, I will tackle this one.
