### ISSUE TITLE
examples/complex_types benchmarks

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#524]
Re-write the example at examples/complex_types in Rust/Motoko and generate corresponding benchmarks.

- [ ] Rust
- [ ] Motoko
- [ ] Azle
- [ ] Benchmarks

**Comment by lastmjs** [comment]
Our benchmarking strategy is now to use the DFINITY benchmarking repo and flamegraphs, or wait for an API that allows us to benchmark canister projects without changing their source code.
