### ISSUE TITLE
examples/motoko_examples/echo benchmarks

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#529]
Re-write the example at examples/motoko_examples/echo in Rust/Motoko and generate corresponding benchmarks.

- [x] Rust
- [x] Motoko
- [x] Azle
- [x] ~~Benchmarks~~
- [x] ~~Add to benchmarks.yaml~~
- [x] Add to test.yaml

**Comment by bdemann** [comment]
echo is just a query and so it will not get benchmarks at this point
