### ISSUE TITLE
examples/motoko_examples/hello-world benchmarks

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#531]
Re-write the example at examples/motoko_examples/hello-world in Rust/Motoko and generate corresponding benchmarks.

- [x] Rust
- [x] Motoko
- [x] Azle
- [x] ~~Benchmarks~~
- [x] ~~Add to benchmarks.yaml~~
- [x] Add to test.yaml

**Comment by bdemann** [comment]
Only queries so we're holding off on benchmarks for now
