### ISSUE TITLE
examples/motoko_examples/http_counter benchmarks

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#532]
Re-write the example at examples/motoko_examples/http_counter in Rust/Motoko and generate corresponding benchmarks.

- [ ] Rust
- [ ] Motoko
- [ ] Azle
- [ ] Benchmarks

**Comment by bdemann** [comment]
Since we can't call any of the functions in the example directly and only one of them is an update anyways Jordan and I decided to not write benchmarks for this example
