### ISSUE TITLE
examples/counter benchmarks

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#538]
Re-write the example at examples/counter in Rust/Motoko and generate corresponding benchmarks.

- [ ] Rust
- [ ] Motoko
- [ ] Azle
- [ ] Benchmarks
- [ ] Add to benchmarks.yaml
- [ ] Add to test.yaml

**Comment by bdemann** [comment]
I'd like to propose getting rid of this example since examples/motoko_examples/counter does the same stuff and more.
Thoughts @dansteren and @lastmjs

**Comment by dansteren** [comment]
Should have responded sooner. I think we've decided to leave this for now but we are focusing on the motoko examples instead. I'm fine if we close this issue (but not delete the example code) unless Jordan thinks this is worth benchmarking after we do the motoko examples.
