### ISSUE TITLE
Azle Compiler Redesign - Query/Update Function Stubs

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#632]
# Query/Update Function Stubs
- [ ] generate function signatures
  - [ ] return type
    - [x] primitive types
      - [x] string/text
      - [x] blob
      - [x] nat/natN
      - [x] int/intN
      - [x] float32/float64
      - [x] bool
      - [x] null
    - [ ] complex types
      - [x] vec
      - [x] opt
      - [ ] record
        - [x] primitive fields
        - [ ] complex fields
          - [x] inline
          - [x] other complex types
          - [x] self-referencing/recursive
      - [ ] variant
         - [ ] primitive fields
         - [ ] complex fields
           - [ ] inline
           - [ ] other complex types
           - [x] self-referencing/recursive
      - [x] func
        - [x] Only pull in funcs used in exported canister methods, rather than **all** `Func` types that we find in all source files.
      - [ ] service
      - [x] principal
      - [x] reserved
      - [x] empty
  - [ ] parameters
    - [x] primitive types
      - [x] string/text
      - [x] blob
      - [x] nat/natN
      - [x] int/intN
      - [x] float32/float64
      - [x] bool
      - [x] null
    - [ ] complex types
      - [x] vec
      - [x] opt
      - [ ] record
        - [x] primitive fields
        - [ ] complex fields
          - [x] inline
          - [ ] other complex types
          - [ ] self-referencing/recursive
      - [ ] variant
         - [ ] primitive fields
         - [ ] complex fields
           - [ ] inline
           - [ ] other complex types
           - [ ] self-referencing/recursive
      - [x] func
      - [ ] service
      - [x] principal
      - [x] reserved
      - [x] empty

**Comment by bdemann** [comment]
Funcs are waiting on https://github.com/dfinity/candid/issues/273 to be resolved for them to be fully implemented. We can't get the function data into the candid type, and without that the candid has to be updated manually in order to reflect what params and return types the func has.
