### ISSUE TITLE
pub-sub Motoko example

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#64]
Recreate the counter Motoko example found here: https://github.com/dfinity/examples/tree/master/motoko/pub-sub

Use the calc Motoko example as a template: https://github.com/demergent-labs/azle/tree/main/examples/motoko_examples/calc

A big reason for recreating the Motoko examples is to find limitations with Azle. Please document any limitations/bugs/errors you find in Azle in this issue thread.

**Comment by di-wu** [comment]
The pub-sub pattern depends on callback functions which can easily define (based on example [func_types](https://github.com/demergent-labs/azle/blob/a26aee7a16dcf105a8335a8a50bd95e60ead983b/examples/func_types/src/func_types.ts)).

```typescript
export type Subscriber = {
    topic: string;
    callback: Func<(counter: Counter) => Oneway<void>>;
}
```

How would a 'fire-and-forget' call work with Azle?

```typescript
let subscribers: Subscriber[] = [];

export function publish(counter : Counter) {
    for (const subscriber of subscribers.values()) {
        if (subscriber.topic == counter.topic) {
            const [ principal ] = subscriber.callback;
            const canister = ic.canisters.CallbackCanister<CallbackCanister>(principal);
            // ERR: A 'yield' expression is only allowed in a generator body.
            yield canister.callback(counter);
        }
    }
}
```

**Comment by lastmjs** [comment]
Implementing all of the Motoko examples is no longer a priority
