### ISSUE TITLE
Importing ManagementCanister results in all its types being exported in candid

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#644]
Current behavior: when running azle on a canister that contains `import { ManagementCanister } from 'azle/canisters/management';` it goes through the definition of ManagementCanister and exports all types that it uses, even if they aren't actively used in the canister method signatures.

Expected behavior: when generating a candid file for a canister, only the types that are used within the service should be exported.

The following examples are currently affected:
- bitcoin
- ethereum_json_rpc
- generators
- management_canister
- motoko_examples/threshold_ecdsa
- outgoing_http_requests

**Comment by lastmjs** [comment]
This is resolved with the Rust rewrite
