### ISSUE TITLE
simple-to-do Motoko example

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#66]
Recreate the simple-to-do Motoko example found here: https://github.com/dfinity/examples/tree/master/motoko/simple-to-do

Use the calc Motoko example as a template: https://github.com/demergent-labs/azle/tree/main/examples/motoko_examples/calc

A big reason for recreating the Motoko examples is to find limitations with Azle. Please document any limitations/bugs/errors you find in Azle in this issue thread.

**Comment by lastmjs** [comment]
Awesome, please review https://github.com/demergent-labs/azle#contributing and especially the https://github.com/demergent-labs/azle/blob/main/LICENSE_EXTENSION.md

**Comment by tarek-eg** [comment]
Should I create a branch or fork the repo?

**Comment by lastmjs** [comment]
Please create your own fork and create a feature branch off of that fork

**Comment by lastmjs** [comment]
I'm going to keep the issue open so that we remember to address the remaining issues once Azle is updated

**Comment by lastmjs** [comment]
There is a problem with the \n character that needs to be looked into

**Comment by lastmjs** [comment]
@tarek-eg considering your work here done and merged, thanks
