### ISSUE TITLE
superheroes Motoko example

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#67]
Recreate the superheroes Motoko example found here: https://github.com/dfinity/examples/tree/master/motoko/superheroes

Use the calc Motoko example as a template: https://github.com/demergent-labs/azle/tree/main/examples/motoko_examples/calc

A big reason for recreating the Motoko examples is to find limitations with Azle. Please document any limitations/bugs/errors you find in Azle in this issue thread.

**Comment by tarek-eg** [comment]
I like to work on this next.

**Comment by lastmjs** [comment]
Sounds good
