### ISSUE TITLE
Ensure that Azle canisters are Candid discoverable

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#692]
For example, we want our canisters to be interacted with from websites like icscan.io. To achieve this, I think there are two paths. One is to have the Candid data stored automatically in the Wasm binary. Another I believe is the __get_temp_hack thing. v0.8.0 of Azle will have __get_temp_hack. We may want to also or instead of that do the Candid service data stored in the binary.

Whatever we do, we should ensure the canisters are discoverable.

Resources:
- https://internetcomputer.org/docs/current/references/ic-interface-spec/#state-tree-canister-information
- https://forum.dfinity.org/t/rfc-canister-metadata-standard/16280
- https://github.com/dfinity/ic-wasm (for reading metadata)
- https://github.com/dfinity/sdk/blob/master/docs/concepts/canister-metadata.md
- https://github.com/Psychedelic/ic-kit/commit/082ea13d6cfbd2d7b945da45ae4d9530960be1df#diff-5dd55cfa837d6176224433e3a1644424adaaa010c65d7d3bdbb95ec9abff629d

**Comment by dansteren** [comment]
This has already been implemented.

**Comment by dansteren** [comment]
Note: https://internetcomputer.org/docs/current/developer-docs/updates/release-notes/#feat-configurable-custom-wasm-sections

**Comment by dansteren** [comment]
Currently `ic-cdk-optimizer` strips out wasm metadata. This means that we currently have to add the metadata after the canister has already been optimized. The best tool for that right now is [ic-wasm](https://github.com/dfinity/ic-wasm). With it was can add candid and whatever custom fields we'd like to the wasm's metadata.
