### ISSUE TITLE
Compiler Cleanup

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#707]
We started our refactor with #674. Building upon that we still need to:

- [ ] Make sure **all** old "info" structures have been changed to the new ACT node types and are located in the appropriate directories
- [ ] Rewrite any imperative functions so that everything is declarative
  - [ ] Functions have one specific purpose
  - [ ] Descriptive function and variable names
  - [ ] Only one level of branching
  - [ ] ? syntax for Option and Result
- [ ] Implement [Rust style guide](https://doc.rust-lang.org/1.0.0/style/) suggestions
  - [ ] mod/use statements are in order
  - [ ] use statements are qualified to the correct depth (no importing functions directly)
  - [ ] Add doc comments on all structs and public functions
  - [ ] etc.
- [ ] Remove unnecessary clones
- [ ] Consider adding randomness implementations and candid code generation into the ACT itself. Figure out how to allow the user to override those, and use the default
- [ ] Consider more specific naming than `to_token_stream`
- [ ] Make sure 1-tuples work
- [ ] get_type_alias_decls for module should be a trait on module
- [ ] generally, we should implement the "get child x" functions on the parent and then those get passed down as fields
- [ ] Pull header into the ACT so that lib doesn't even have a quote
- [ ] Remove `eprintln`s used in debugging
- [ ] In TsAst's `.to_act` we should abstract this away more. It's too imperative right now. Essentially have one line for each field that we put on the AbstractCanisterTree, and the rest is just abstracted away.
- [ ] Name variables act_canister_method_node_queries
- [ ] The current traits are messy. Put them in a common folder or make them consistent. Unify ones where it makes sense.
- [ ] mod.rs files are just a dumping ground. Generally we should only have sub-mods in mod. Figure this out.
- [ ] SystemStructureType. Code smell. There's only one arm on this so figure out if it should be removed or fleshed out
- [ ] Figure out when to use ActNode vs the more specific nodes.
- [ ] Is AbstractCanisterTree fully generic or fully specific. Choose one.
- [ ] Decide the specificity of ActNodes. ActDataType node is very broad, but then ActNode only has two variants. We haven't really broken things up at the right level nor know how to yet. (I think these last 3 bullet points are the same. Hard to explain)
- [ ] Consider cleaning up data_types_nodes/mod.rs (like other mod.rs files). Maybe things that we own we can just stick on an impl, not in a trait.

**Comment by lastmjs** [comment]
Can we go through this and check off what we can?
