### ISSUE TITLE
Azle Canister Decl Errors

### ISSUE THREAD

**Issue by bdemann** [demergent-labs/azle#737]
Part of [Compiler Errors v2](https://github.com/demergent-labs/azle/issues/797)

As long as we are working on errors, one of the errors that the azle canister decl has is when it's doing the get dependencies. I am wondering about whether or not we should have any checking for compiler errors in the get dependencies?

**Comment by bdemann** [comment]
For example, when we are collecting dependencies from azle_type_elements we know very little about what type we are looking at, it could be canister it could be a variant, it could be a record, so instead of having a vague error while we are collecting dependencies, we could just return an empty hash set, in effect saying "This unsupported type doesn't have any dependencies that we need to find" and then we reserve the error for later in the process when we know much more about what we are handling

**Comment by dansteren** [comment]
This is no longer an issue now that we have offloaded the get_dependencies pass to the CDK Framework.
