### ISSUE TITLE
Expunge todos panics and unwraps

### ISSUE THREAD

**Issue by bdemann** [demergent-labs/azle#741]
- [x] todo
    - [x] ts_ast/ast_traits/get_name.rs
        - [x] GetName for Expr has 36
    - [x] ts_ast/ts_method_signature.rs
        - [x] None => todo!("Canister Method must have a return type")
    - [x] ts_ast/azle_functions_and_methods/ts_fn_param.rs
        - [x] Get Name for TsFnParam has 3
        - [x] GetTsTYpe for TsFnParam has 3
    - [x] -generators/type_aliases.rs- moved to -> azle_type_alias_decl.rs https://github.com/demergent-labs/azle/issues/744
        - [x] todo!("ERROR: Dependant Type [{dependant_type_name}] not found type alias list!")
    - [x] cdk_act/nodes/data_type_nodes/act_data_type.rs
        - [x] as_type_alias for Primitive, Option, TypeRef, and Array
- [x] unwrap
    - [x] ts_ast/
        - [x] azle_functions_and_methods/mod.rs
        - [x] ts_ast.rs
        - [x] module.rs
    - [x] generators/
        - [x] type_aliases.rs
    - [x] cdk_act/nodes/data_type_nodes/
        - [x] act_funcs.rs
- [x] panic
    - [x] ts_ast/program/system_canister_method_builder/
        - [x] init.rs
        - [x] pre_upgrade.rs
        - [x] inspect_message.rs
        - [x] post_upgrade.rs
        - [x] heartbeat.rs
    - [x] ts_ast/azle_functions_and_methods/
        - [x] ts_fn_param.rs
        - [x] mod.rs
    - [x] ts_ast/
        - [x] ts_ast.rs

**Comment by bdemann** [comment]
generators/type_aliases.rs
`todo!("ERROR: Dependant Type [{dependant_type_name}] not found type alias list!")`
If this error happens then that means we can't find where the type is which means we can't get any code information from it.
Maybe we would be able get the code from where the dependency is made?

**Comment by bdemann** [comment]
I'm unsure how to best handle the panics in ts_ast.rs, I converted all of the unwraps into panics and cleaned them up a little. I think they are good enough for right now.

**Comment by bdemann** [comment]
module.rs has some unwraps but they are all in maps that happen after a filter that filters out anything that would possibly fail that unwrap.

**Comment by dansteren** [comment]
Moved everything related to cross-canister function calls out to #743.
