### ISSUE TITLE
More in-depth installation explanation

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#79]
Explain everything that must be installed

- [x] Ubuntu
  - [x] Rust
  - [x] wasm32-unknown-unknown
  - [x] error: linker `cc` not found (sudo apt install build-essential)
  - [x] is `cmake` not installed? (sudo apt install cmake)

**Comment by filharvey** [comment]
I've installed Ubuntu 20.04. Installed Rust, added wasm32-unknown-unknown, installed cc, installed cmake. 

ran npm install in the example directory

tried to go into an example (counter) and tried running, but get this error.

`ubuntu@ip-172-31-41-104:~/azle/examples/counter$ dfx deploy
Deploying all canisters.
All canisters have already been created.
Building canisters...
Executing 'azle counter'
thread 'main' panicked at 'Could not run custom tool.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/dfx/src/lib/builders/custom.rs:186:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by lastmjs** [comment]
Perhaps it's the following: in your dfx.json, the build property should be `npx azle counter` or `node_modules/.bin/Azle counter`.
