### ISSUE TITLE
Compiler Errors v2

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#797]
- [x] https://github.com/demergent-labs/azle/issues/737

**Comment by bdemann** [comment]
azle_functions_and_methods/mod.rs has some errors that don't use the ErrorMessages so they could be more helpful than they presently are. I'm thinking if we could add a trait restraint with a trait that lets us access the source map that would do the trick.

**Comment by dansteren** [comment]
This ticket was the Epic level ticket before we adopted ZenHub. As such I'm closing this out in favor of using the [🄴 Errors Infrastructure](https://github.com/demergent-labs/azle#workspaces/engineering-63eff82fd9fe250011f32225/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTIxMzQ3) ZenHub epic.

With regards to Ben's comment above, the file "azle_functions_and_methods/mod.rs" is no longer present in the codebase. However, any place that doesn't use the ErrorMessage struct will likely need to be reworked to have a nice annotated snippet included with it. That is work that will take place in the [🄴 Very Very Nice Error Messages](https://github.com/demergent-labs/azle#workspaces/engineering-63eff82fd9fe250011f32225/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTE5NDg1) epic.
