### ISSUE TITLE
Using generics in Records/Variants doesn't return a nice error message

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#917]
Generics in Records/Variants are not currently supported. However, when used, developers are presented with obscure error messages. We should detect the usage of generics and give a nice error message to the developer.

For example, given the following code:
```ts
export type InsertResult<T> = Variant<{
    ok: T;
    err: InsertError;
}>;
```
The user is currently given this error message:
```
...
error[E0412]: cannot find type `T` in this scope
    --> canisters/azle/src/lib.rs:2354:8
     |
2353 | enum InsertResult {
     |                  - help: you might be missing a type parameter: `<T>`
2354 |     ok(T),
     |        ^ not found in this scope
...
```
...plus **a lot** more unhelpful text.

But should get something more like this:
```
💣 Unsupported generic in variant InsertResult
    --> src/index.ts:6:9
  |
6 |     ok: T
  |         ^
help: Remove this generic type or make it concrete
  |
6 |     ok: string
  |         ^^^^^^
```

**Comment by lastmjs** [comment]
This will no longer be a problem once this is implemented, which is imminent: https://github.com/demergent-labs/azle/issues/230
