### ISSUE TITLE
Update all dependencies to latest, especially ic-stable-structures and Boa

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#940]
- [x] dfx
  - [x] Fix stable memory, outgoing http requests and ethereum rpc examples
- [x] Rust
  - [x] Make it so that you just have to copy over the old directory if the Rust version is the same
- [x] ic-cdk
- [x] ic-cdk-macros
- [x] candid
- [x] ic-cdk-timers
- [x] Boa
  - [x] time
  - [x] Clean up uint8array
    - [x] From and into should be best possible
    - [x] Run performance tests
  - [x] Clean up promises
    - [x] Use cleaner APIs
    - [x] Try to use NativeAsyncFunctions
- [x] ic-stable-structures
  - [x] I don't think funcs or services can be used as keys in stable structures now because I don't know how to use derive macros on those macros...we would have to implement these things manually
  - [x] make sure to test all candid types in Rust, the non-primitive types from the candid library, we might need to implement ord etc on them
- [x] Cargo.lock
- [x] We need to study and look into how bad our float64/float32 0rd and Eq trait implementations are
- [x] Use new Promise API
- [ ] Check for latest updates and do Cargo.lock one more time
- [x] Use crazy script to update all candid files in Azle
- [x] Native async functions
- [x] Consider deeper documentation on the limitations of promises, apparently the queue isn't very advanced
- [x] We should explain the caveats with using float64, float32, service, and func as keys in stable structures
- [x] Open issue in Boa for job_queue ownership
- [x] We need to copy instead of mv for the Rust thing
- [x] Will there be a problem with the wrapper type in the generated Candid? We need it to be identical...
- [x] We might be able to just use the wrapper float types everywhere somehow, I don't think the candid is changing. Let's check on that
- [x] Update to latest boa that fixes wasm issues and job queue ownership issue
- [x] Use one target directory for everything, literally everything

This now appears in the outgoing http request example replica logs:

```
FIX ME! opt table3 <: opt record {
  function : func (
      record {
        context : vec nat8;
        response : record {
          status : nat;
          body : vec nat8;
          headers : vec record { value : text; name : text };
        };
      },
    ) -> (
      record {
        status : nat;
        body : vec nat8;
        headers : vec record { value : text; name : text };
      },
    ) query;
  context : vec nat8;
} via special opt rule.
This means the sender and receiver type has diverged, and can cause data loss.
```

**Comment by dansteren** [comment]
This is currently blocked by the Finalize CDK Inteface and Finalize Syntax epics.

**Comment by lastmjs** [comment]
No longer blocked for me, just need to implement Vec

**Comment by lastmjs** [comment]
Actively working on this now
