### ISSUE TITLE
Azle Book: High latencies

### ISSUE THREAD

**Issue by domwoe** [demergent-labs/azle#950]
In the section on [high latencies](https://demergent-labs.github.io/azle/azle.html#high-latencies) you write

> Also cross-canister request latencies build up linearly. If canister A calls canister B calls canister C, then you can multiply the latency by the total number of calls.

You should make clear that this is in many cases only true if A, B, and C are each on different subnets. If they are on the same subnet, and the subnet is not under heavy load then there's a good chance that the entire call stack can be executed in one round of consensus. From my experience of talking to IC devs, this is a common misunderstanding, that each inter-canister update call will lead to a linear increase in latency. 

Btw. I really like this sober presentation of the Benefits and Drawbacks targeted to web developers!

**Comment by lastmjs** [comment]
Perfect, I really appreciate this suggestion. I'll get this issue into our flow.

**Comment by lastmjs** [comment]
Live: https://demergent-labs.github.io/azle/azle.html#high-latencies
