### ISSUE TITLE
Guard functions don't work on init and post_upgrade methods

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#954]
Because Azle needs to create a VM to evaluate the JS code, we currently cannot support guard functions on `init` and `post_upgrade` methods.

**Comment by lastmjs** [comment]
I think we can solve this by initializing the vm in the guard function if it does not already exist. So we would possibly initialize the vm in init, post_upgrade, or guard functions.

**Comment by lastmjs** [comment]
Guard functions are not allowed on init or post_upgrade it turns out
