### ISSUE TITLE
Cant compile counter example

### ISSUE THREAD

**Issue by filharvey** [demergent-labs/azle#96]
After changing the compile to 'npm azle counter'

The next issue I'm getting is 

`error[E0412]: cannot find type `nat64` in this scope
   --> src/src/lib.rs:119:33
    |
119 |         async fn readCount() -> nat64 {
    |                                 ^^^^^ not found in this scope
`

Im on windows with ubuntu 20 installed.

**Comment by filharvey** [comment]
Of note I can compile the Motoko example calc.

**Comment by lastmjs** [comment]
The examples are not fully up to date yet with the new compiler infrastructure I am putting in place. This will be resolved soon

**Comment by filharvey** [comment]
I saw that, thanks. Others compiled ok.

**Comment by lastmjs** [comment]
This is now fixed and live
