### ISSUE TITLE
Reduce disk space usage

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#963]
I just looked at my disk usage for Azle. My `~/.config/azle` folder is currently ~43GB. I have 4 versions installed, some being ~16GB. I think this is far too large and a lot of waste. We should consider ways to remove old versions of azle and generally reduce the size of our installs. We should also build an `npx azle clean` command that let people remove old installs or something.

**Comment by lastmjs** [comment]
We have done a lot to reduce the size of `~/.config/azle` by having one directory per Rust version and sharing one target directory across all Rust/Azle versions. We have yet to introduce a clean command.

**Comment by lastmjs** [comment]
We are introducing a new command `npx azle clean` that will delete the entire `~.config/azle` directory. In the future we will expand the functionality of the clean command with subcommands: https://github.com/demergent-labs/azle/issues/1137
