### ISSUE TITLE
Robust imports

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#987]
Right now our import system has a number of issues:

- [x] * syntax doesn't work for Azle types
- [x] Renaming imports doesn't work for Azle types
- [x] Parsing of Azle types is based off of simple strings without regards to import names or paths
- [x] Research existing solutions/algorithms
- [x] Look into TS module resolution
- [x] Make sure that all types that come from 'azle' are taken into account, for example Alias or GuardResult

Generally speaking, our import system is not robust. If developers use types with the same names as those exported from Azle, compiler issues may occur. We should address this issue, though we foresee it being a significantly complex effort.

**Comment by lastmjs** [comment]
For each file:
  determine the name of the Azle type that you're searching for

Determining the name of the A zle type that you're searching for:

**Comment by lastmjs** [comment]
Here's some example code:

```typescript
import { blob, match, Result, $update, Record as Chunky } from 'azle';
import { managementCanister } from 'azle/canisters/management';
import { Record } from 'azle';
import { Monkey } from './test1';
import * as Lunky from './test1';

type Record1 = Monkey<{}>;
type Record2 = Chunky<{}>;
type Record3 = Lunky.Monkey<{}>;
type Record4 = Record<{}>;

```

**Comment by bdemann** [comment]
- Visitor Pattern: You can use the Visitor pattern to traverse the AST and identify the type references you're interested in. By implementing a visitor that specifically targets type references, you can visit each node in the AST and perform the necessary checks to determine if it corresponds to the "Record" type. This pattern allows you to separate the traversal logic from the type-specific logic, making it easier to maintain and extend.
- 
- Symbol Table: As mentioned earlier, a symbol table can be constructed during AST traversal. While traversing the AST, you can populate the symbol table with the relevant information about imported symbols, their aliases, and the corresponding type references. This symbol table can later be queried to resolve the actual name of the "Record" type reference, even if it has been renamed or imported from different packages.
- 
- Name Resolution: Name resolution algorithms can help you handle scenarios where the imported symbol name or type name has changed. By applying name resolution rules specific to TypeScript, you can track the imported symbols and their aliases, determine the correct type reference name, and resolve any renaming or importing discrepancies.

By combining these techniques, you can traverse the AST, build a symbol table, perform name resolution, and finally extract the correct type reference name for the "Record" type, even if it has been renamed or imported from different packages.

**Comment by lastmjs** [comment]
Once we decide to analyze aliases, we'll need to think of cases like this:

```typescript
type MonkeyAlias<T extends object> = test1.Monkey<T>;

type Yo = MonkeyAlias<{
    prop1: string;
}>;
```

**Comment by bdemann** [comment]
This has been broken up into sub tickets
